---
- name: PHP | Add php-7.1 PPA
  apt_repository: repo='ppa:ondrej/php'
                  state=present
                  update_cache=yes

- name: PHP | install php packages
  apt: pkg={{ item }} state=installed
  with_items: "{{ php_packages }}"

- name: PHP | FPM php.ini
  template:
    src=php.ini.j2
    dest=/etc/php/7.1/fpm/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644

- name: PHP | CLI php.ini
  template:
    src=php.ini.j2
    dest=/etc/php/7.1/cli/php.ini
    backup=yes
    owner=root
    group=root
    mode=0644

- name: PHP | configure opcache
  template:
    src=opcache.ini.j2
    dest=/etc/php/7.1/mods-available/opcache.ini
    backup=yes
    owner=root
    group=root
    mode=0644

- name: PHP | configure for nginx 1
  lineinfile: dest=/etc/php/7.1/fpm/pool.d/www.conf regexp="^[#|;]?group = www" insertafter="^[#|;]?group = www" line="group = vagrant"

- name: PHP | configure for nginx 2
  lineinfile: dest=/etc/php/7.1/fpm/pool.d/www.conf regexp="^[#|;]?listen\.group = www" insertafter="^[#|;]?listen\.group = www" line="listen.group = vagrant"

- name: PHP | configure for nginx 3
  lineinfile: dest=/etc/php/7.1/fpm/pool.d/www.conf regexp="^[#|;]?listen\.mode = 0660" insertafter="^[#|;]?listen\.mode = 0660" line="listen.mode = 0660"
  notify:
    - restart nginx
    - restart fpm
