# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|

  config.vm.box = "ubuntu/trusty32"

  # Configure the network interfaces
  config.vm.network :private_network, ip:    "192.168.33.12"
  config.vm.network :forwarded_port,  guest: 80,    host: 8080
  config.vm.network :forwarded_port,  guest: 8081,  host: 8081
  config.vm.network :forwarded_port,  guest: 3306,  host: 3306
  config.vm.network :forwarded_port,  guest: 27017, host: 27017


  # Configure shared folders
  config.vm.synced_folder ".",  "/vagrant", id: "vagrant-root", :nfs => true
  config.vm.synced_folder "..", "/var/www", id: "application",  :nfs => true

  config.vm.provider :virtualbox do |vb|
    vb.name = "Manolo"
    vb.customize ["modifyvm", :id, "--memory", "4096"]
  end

  config.vm.provision :shell, path: "shell/vagrant_main_provision.sh"

end
