---
- name: Manolo playbook :)
  hosts: "webservers"
  become: true
  become_user: root
  handlers:
    - include: handlers/services.yml
  roles:
    - nginx
    - php
    - phpunit
    - geerlingguy.memcached
    - geerlingguy.ntp
    - composer
    - curl
    - git
    - nodejs
    - wget